baseurl = "/"
title = "saerpa's blog"
copyright = "Don't worry, be happy :)"
languageCode = "zh-CN"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Categories"
  weight = -100
  identifier = "category"
  url = "/categories/"

[author]
  name = "saerpa"

[params.meta]
  keywords = ""
  description = "Personal blog."

[params]
  email = "saerpa@163.com"
  github = "saerpa"
  #gitlab = "gitlab id"
  #twitter = "twitter id"
  #linkedin = "linkedin id"
